version: "3.3"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    expose:
      - 5998

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "5998:5998"
